import React, { ReactNode, useState } from "react";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import Head from "next/head";

const Layout = ({ children }: { children: ReactNode }) => {
  const [searchQuery, setSearchQuery] = useState("");
  const [startSearch, setStartSearch] = useState<boolean>(false);

  const { push } = useRouter();
  const handleSearch = (event: any) => {
    event.preventDefault();
    push(`/movie/${searchQuery}`);
    setStartSearch(true);

    console.log("searchQuery", searchQuery);
  };
  return (
    <>
      <Head>
        <title>Uptick Lookup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>movLibrary</h1>

        <form action="" onSubmit={handleSearch}>
          <label htmlFor="search"></label>
          <input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            type="text"
            name="search"
            placeholder="Search movies"
          />
          <button type="submit">Search</button>
        </form>
      </header>

      <main className={styles.main}>{children}</main>
    </>
  );
};

export default Layout;
